\section*{Section 1:}

\section*{Control Valve Sizing and Selection}

\section*{Chapter 1}

\section*{Control Valve Selection}

Picking a control valve for a particular application used to be straightforward. Usually only one general type of valve was considered, a sliding-stem valve. Each manufacturer offered a product suitable for the job, and the choice among them depended upon such obvious matters as cost, delivery, vendor relationships and user preference.

Today, control valve selection is considerably more complex, especially for engineers with limited experience or those who have not kept up with changes in the control valve industry.

For many applications, an assortment of slidingstem and rotary valve styles are available. Some are touted as "universal" valves for almost any size and service, while others are claimed to be optimum solutions for narrowly defined needs. Even the most knowledgeable user may wonder whether they are really getting the most for their money in the control valves they have been specifying.

Like most decisions, selection of a control valve involves a great number of variables. Presented here is an overview of the selection process. The discussion includes categorization of available valve types and a set of criteria to be considered in the selection process.

\section*{General Categories of Control Valves}
"Control valve" in this discussion means any pow-er-operated valve, whether used for throttling or for on-off control. Other valve varieties such as motorized gate valves, louvers, pinch valves and self-operated regulators are not considered here.

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-007.jpg?height=885&width=462&top_left_y=696&top_left_x=1257}
\captionsetup{labelformat=empty}
\caption{Figure 1-1. Modern control valve combines actuator, valve assembly and digital valve controller to provide maximum performance in a wide variety of control applications.}
\end{figure}

The major valve types, sliding-stem and rotary, are further divided within Table 1-2 into a total of nine subcategories according to relative performance and cost. Despite variations found within each category, such as cage-guiding versus stem-guiding, all valves within a given subcategory may be considered very much alike in the early stages of the selection process.

Selecting a valve involves narrowing down to one of these nine subcategories and then comparing specific valves in that group.

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-008.jpg?height=1026&width=961&top_left_y=284&top_left_x=552}
\captionsetup{labelformat=empty}
\caption{Figure 1-2. Standard globe sliding-stem valve design is typified by the ET. A broad range of sizes, materials and end connections is available. The balanced plug reduces plug force and allows use of smaller actuators. These valves are the first choice for applications less than NPS 3 size.}
\end{figure}

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-008.jpg?height=866&width=828&top_left_y=1501&top_left_x=655}
\captionsetup{labelformat=empty}
\caption{Figure 1-3. Severe service capability in globe valves demonstrated by this Large ET. The drilled hole cage provides attenuation of flow noise by splitting the flow into multiple passages. Spacing of the holes is carefully controlled to eliminate jet interaction and higher resultant noise levels.}
\end{figure}

\section*{Sliding-Stem Valves}

The most versatile of control valves are the slidingstem designs. Globe, angle, and Y-pattern valves can be purchased in sizes ranging from NPS 1/236. More choices of materials, end connections and control characteristics are included here than in any other product family.

Globe valves are available in cage-guided, postguided and stem-guided designs, with flanged, screwed or weld ends. Economical cast iron as well as carbon steel, stainless steel and other high-performance body materials are available. Available valve body pressure ratings range to ASME CL4500 or API 10,000.

The globe valve's precise throttling capabilities, overall performance and general sturdiness make them a bargain despite their slight cost premium. With the globe valve, the buyer gets a rugged, dependable unit intended for long, trouble-free service.

Sliding-stem valves are ruggedly built to handle field conditions such as piping stress, vibration, and temperature changes. In sizes through NPS 3 -4 , incremental costs over rotary valves are low in contrast to the increments in benefits received.

For many extreme service conditions, sliding-stem valves are the only suitable choice. These situations include high pressures and temperatures, excessive noise, and the potential for cavitation. Due to process demands, these applications require the rugged construction of the sliding-stem design.

Barstock valves are small, economical slidingstem valves featuring bodies machined from bar stock. Body sizes range from fractions of NPS 1 3; flow capacities generally are lower than those of general purpose valves. End connections usually are flangeless (for mounting between piping flanges) or screwed.

The main advantage of the barstock valve is that far more materials are readily available in bar form than in cast form. Consequently, these valves are often used where there are special corrosion considerations.

Also, the compactness and general high-quality construction of barstock valves make them attractive for low flow rate applications. Overall, they are an economical choice when they can be used.

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-009.jpg?height=684&width=671&top_left_y=281&top_left_x=1192}
\captionsetup{labelformat=empty}
\caption{Figure 1-4. EHD is typical of high-pressure globe valves. Rated at ASME CL2500, it provides throttling control of high-pressure steam and fluids. Anti-noise and anti-cavitation trims are available to handle flow problems.}
\end{figure}

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-009.jpg?height=717&width=711&top_left_y=1230&top_left_x=1184}
\captionsetup{labelformat=empty}
\caption{Figure 1-5. NPS 1 Baumann 24000 Little Scotty valve with a size 32 actuator and a FIELDVUE DVC6200}
\end{figure}

The third subcategory, which involves the lowest cost products among sliding-stem valves, utilizes "economy" bodies (Figure 1-5). These valves are used for low-pressure steam, air and water applications that are not demanding. Sizes available range from NPS 1/2-4. Body materials include bronze, cast iron, steel and SST. Pressure classes generally stop at ASME CL300. Compared to regular sliding-stem valves, these units are very simple; their actuators are smaller, and their construc-

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-010.jpg?height=608&width=1183&top_left_y=295&top_left_x=482}
\captionsetup{labelformat=empty}
\caption{Figure 1-6. High-pressure ball valves feature heavy shafts and full ball designs. This V250 is suitable for pressure drops to 2220 psig. ASME CL600 and CL900 bodies are available-sizes range to NPS 24.}
\end{figure}

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-010.jpg?height=440&width=1001&top_left_y=1138&top_left_x=596}
\captionsetup{labelformat=empty}
\caption{Figure 1-7. Applications to ASME CL600 can be handled by the V150/V200/V300 Vee-Ball ${ }^{\text {m }}$. This product incorporates many features to improve throttling performance and rangeability. Tight shutoff is achieved by using either heavy-duty metal seals or composition seals.}
\end{figure}
tion is economical. Severe service trims for noise and cavitation service are not available in these products.

\section*{Ball Valves}

There are two subcategories of ball valves. The through-bore or full-ball type illustrated in Figure 1-6 is used typically for high pressure drop throttling and on-off applications in sizes to NPS 24. Full port designs exhibit high flow capacity and low susceptibility to wear by erosive streams. However, sluggish flow response in the first 20\% of ball travel may make full-bore ball valves unsuitable for some throttling applications.

Another popular kind of ball valve is the seg-mented-ball style (Figure 1-7). This subcategory utilizes a reduced bore, and the edge of the ball segment has a contoured notch shape for better throttling control and higher rangeability. Intended primarily for modulating service, segmented-ball valves are generally higher in overall control performance than full-ball products.

Segmented-ball valves with their splined shaft connections are engineered to eliminate lost motion, which is detrimental to performance. The use of heavy-duty metal and fluoroplastic sealing elements allows wide temperature and fluid applicability. Their straight-through flow design achieves high capacity with sizes ranging through NPS 24 and pressure ratings to ASME CL600. Price is generally lower than that of globe valves.

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-011.jpg?height=763&width=1562&top_left_y=292&top_left_x=295}
\captionsetup{labelformat=empty}
\caption{Figure 1-8. The V500 eccentric plug valve is specially designed for severe rotary applications. Since the valve plug "cams" into the seat ring upon closure, it features tight shutoff with globe valve style seating. It also offers excellent resistance to abrasive wear and flashing induced erosion.}
\end{figure}

\section*{Eccentric Plug Valves}

This class of valves combines many features of sliding-stem and rotary products. Eccentric plug valves feature rotary actuation. But, unlike most rotary valves, this product utilizes a massive, rigid seat design.

Eccentric-plug valves (Figure 1-8) exhibit excellent throttling capability and resistance to erosion. Thus, many of the good aspects of both rotary and sliding-stem designs are combined.

Sizes generally range through NPS 8; pressure ratings go to ASME CL600. Both flanged and flangeless body styles are available in a variety of materials.

The requirement for zero or low leakage gave rise to new designs such as the lined and high performance butterfly valves (BFV's).

Lined butterfly valves feature an elastomer or fluoropolymer (TFE) lining that contacts the disk to provide tight shutoff. Since this valve design depends on interference between the disc and liner for shutoff, it is more limited in pressure drop. Temperature ranges typically are limited due to the elastomer disk seal.

In addition to serving as the disk seal, the liner also protects the inner bore of the valve body from the process fluid, which allows these valves to be used in many corrosive situations. Elastomer-lined BFV's are generally the lowest price products available as control valves in medium to large sizes.

Heavy shafts and discs, full-rated bodies and sophisticated seals that allow tight shutoff against high pressures characterize high performance but-

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-012.jpg?height=454&width=1462&top_left_y=292&top_left_x=355}
\captionsetup{labelformat=empty}
\caption{Figure 1-9. High performance butterfly valves provide excellent performance and value. High-pressure capability, tight shutoff and excellent control are featured as standard. This 8560 design is made for ASME CL150 applications.}
\end{figure}
terfly valves such as the one in Figure 1-9. These valves provide an excellent combination of performance features, lightweight and very reasonable pricing.

In offset disc designs, eccentric shaft mounting allows the valve disc to swing clear of its seal to minimize wear and torque. The offset disc allows uninterrupted sealing and a seal ring that can be replaced without removing the disc. High performance butterfly valves come in sizes from NPS 2 through NPS 72, with flangeless, lugged, double flanged connections, carbon steel or stainless steel bodies, and pressure ratings to ASME CL2500. Tight metal-to-metal seals, made possible with advanced eccentric design, provide tight shutoff in applications that are too hot for elastomer lined valves. Considering this tight shutoff capability and heavy-duty construction, high performance butterfly valves can be a suitable option to many applications where sliding-stem valves are normally specified.

\section*{General Selection Criteria}

Most of the considerations that guide the selection of valve type and brand are rather basic. However, there are some matters that may be overlooked by users whose familiarity is mainly limited to just one or a few valve types. Table 1-1 below provides a checklist of important criteria; each is discussed at length following the table.

\section*{Pressure Ratings}

Body pressure ratings ordinarily are considered according to ASME pressure classes-the most common ones for steel and stainless steel being

Classes 150, 300 and 600. (Source documents are ASME/ANSI Standards B16.34, "Steel Valves," and ANSI/ASME B16.1, "Cast Iron Pipe Flanges and Flanged Fittings.") For a given body material, each ASME Class corresponds to a prescribed profile of maximum pressures that decrease with temperature according to the strength of the material. Each material also has a minimum and maximum service temperature based on loss of ductility or loss of strength. For most applications, the required pressure rating is dictated by the application. However, since all products are not available for all ASME Classes, it is an important consideration for selection.

\begin{table}
\captionsetup{labelformat=empty}
\caption{Table 1-1. Suggested General Criteria for Selecting Type and Brand of Control Valve}
\begin{tabular}{|l|}
\hline Body pressure rating \\
\hline High and low temperature limits \\
\hline Material compatibility and durability \\
\hline Inherent flow characteristic and rangeability \\
\hline Maximum pressure drop (shutoff and flowing) \\
\hline Noise and cavitation \\
\hline End connections \\
\hline Shutoff leakage \\
\hline Capacity versus cost \\
\hline Nature of flowing media \\
\hline Dynamic performance \\
\hline
\end{tabular}
\end{table}

\section*{Temperature Considerations}

Required temperature capabilities are also a foregone conclusion, but one that is likely to narrow valve selection possibilities. The considerations include the strength or ductility of the body material as well as relative thermal expansion of various parts.

Temperature limits also may be imposed due to disintegration of soft parts at high temperatures or
loss of resiliency at low temperatures. The soft materials under consideration include various elastomers, plastics, and PTFE. They may be found in parts such as seat rings, seal or piston rings, packing, rotary shaft bearings and butterfly valve liners. Typical upper temperature limits for elastomers are in the $200-350^{\circ} \mathrm{F}\left(93-176^{\circ} \mathrm{C}\right)$ range, and the general limit for PTFE is $450^{\circ} \mathrm{F}\left(232^{\circ} \mathrm{C}\right)$.

Temperature affects valve selection by excluding certain valves that do not have high- or low-temperature options. It also may have some effect on the valve's performance. For instance, going from PTFE to metal seals for high temperatures generally increases the shutoff leakage flow. Similarly, high temperature metal bearing sleeves in rotary valves impose more friction on the shaft than do PTFE bearings, so that the shaft cannot withstand as high a pressure-drop load at shutoff. Selection of valve packing is also based largely on service temperature.

\section*{Material Selection}

The third criterion in Table 1-1, material compatibility and durability, is a more complex consideration. At issue may be corrosion by the process fluid, erosion by abrasive material, flashing, cavitation or simply a matter of process pressure and temperature. The piping material usually indicates the body material. However, since velocity is higher in valves other factors must be considered. When these items are included, often valve and piping materials will differ. The trim materials, in turn, are usually a function of the body material, temperature range and qualities of the fluid.

\section*{Flow Characteristic}

The next selection criterion, inherent flow characteristic, refers to the pattern in which the flow at constant pressure drop changes according to valve position.

Typical characteristics are quick-opening, linear and equal-percentage. The choice of characteristic may have a strong influence on the stability or controllability of the process (see Table 1-3), since it represents the change of valve gain relative to travel.

Most control valves are carefully "characterized" by means of contours on a plug, cage, or ball ele-

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-013.jpg?height=681&width=703&top_left_y=276&top_left_x=1176}
\captionsetup{labelformat=empty}
\caption{Figure 1-10. Many control valves offer a choice of characteristic. Selection to match process requirements is guided by simple rules. Adherence to these guidelines will help assure stable operation.}
\end{figure}
ment. Some valves are available in a variety of characteristics to suit the application, while others offer little or no choice. To quantitatively determine the best flow characteristic for a given application, a dynamic analysis of the control loop can be performed.

The accompanying drawing illustrates typical flow characteristic curves (Figure 1-10). The quick opening flow characteristic provides for maximum change in flow rate at low valve travels with a fairly linear relationship. Additional increases in valve travel give sharply reduced changes in flow rate, and when the valve plug nears the wide open position, the change in flow rate approaches zero. In a control valve, the quick opening valve plug is used primarily for on-off service.

The linear flow characteristic curve shows that the flow rate is directly proportional to the valve travel. This proportional relationship produces a characteristic with a constant slope so that, with constant pressure drop, the valve gain will be the same at all flows. The linear valve plug is commonly specified for liquid level control and for certain flow control applications requiring constant gain.

In the equal percentage flow characteristic, equal increments of valve travel produce equal percentage changes in the existing flow. The change in flow rate is always proportional to the flow rate just before the change in valve plug, disc, or ball position is made. When the valve plug, disc, or ball is near its seat and the flow is small, the change in
flow rate will be small; with a large flow, the change in flow rate will be large.

An equal percentage flow characteristic is used generally on pressure control applications and on other applications where a large percentage of the pressure drop is normally absorbed by the system itself with only a relatively small percentage available at the control valve. Valves with an equal percentage characteristic should also be considered where highly varying pressure drop conditions could be expected.

\section*{Rangeability}

Another aspect of a valve's flow characteristic is its rangeability, which is the ratio of its maximum and minimum controllable flow rates. Exceptionally wide rangeability may be required for certain applications to handle wide load swings or a combination of start-up, normal and maximum working conditions. Generally speaking, rotary valves-especially partial ball valves-have greater rangeability than sliding-stem varieties.

\section*{Use of Positioners}

A positioner is an instrument that helps improve control by accurately positioning a control valve actuator in response to a control signal. They are useful in many applications and are required with certain actuator styles in order to match actuator and instrument pressure signals or to provide operating stability. To a certain extent, a valve with one inherent flow characteristic can also be made to perform as though it had a different characteristic by using a nonlinear (i.e., characterized) posi-tioner-actuator combination. The limitation of this approach lies in the positioner's frequency response and phase lag compared to the characteristic frequency of the process.

Although it is common practice to use a positioner on every valve application, each application should be reviewed carefully.

\section*{Pressure Drop}

The maximum pressure drop a valve can tolerate at shutoff or when partially or fully open is an important selection criteria. Sliding-stem valves are generally superior in both regards because of the
rugged nature of their moving parts. Many rotary valves are limited to pressure drops well below the body pressure rating, especially under flowing conditions, due to dynamic stresses that high velocity flow imposes on the disk or ball segment.

\section*{Noise and Cavitation}

Noise and cavitation are two considerations that often are grouped together because both may result from high pressure drops and large flow rates. They are treated by special modifications to standard valves. Chapter 5 discusses noise generation and abatement, while Chapter 6 discusses the cavitation phenomenon and its impact and treatment.

\section*{End Connections}

The three common methods of installing control valves in pipelines are by means of screwed pipe threads, bolted flanges, and welded end connections. At some point in the selection process, the valve's end connections must be considered with the question simply being whether the desired connection style is available in the valve being considered. Maintenance, weight, size, and service conditions all contribute to what end connection is used.

In some situations, this matter can limit the selection rather narrowly. For instance, if a piping specification calls for welded connections only, the choice usually is limited to sliding-stem valves.

Screwed end connections, popular in small control valves, offer more economy than flanged ends. The threads usually specified are tapered female NPT (National Pipe Thread) on the valve body. They form a metal-to-metal seal by wedging over the mating male threads on the pipeline ends. This connection style is usually limited to valves not larger than NPS 2, and is not recommended for elevated temperature service.

Valve maintenance might be complicated by screwed end connections if it is necessary to take the body out of the pipeline. Screwed connections require breaking a flanged joint or union connection to permit unscrewing the valve body from the pipeline.

Flanged end valves are easily removed from the piping and are suitable for use through the range
![](https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-015.jpg?height=749&width=578&top_left_y=287&top_left_x=349)

A7098 RING-TYPE JOINT
Figure 1-11. Popular varieties of bolted flange end connections.

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-015.jpg?height=530&width=438&top_left_y=1221&top_left_x=403}
\captionsetup{labelformat=empty}
\caption{Figure 1-12. Common welded end connections.}
\end{figure}
of working pressures that most control valves are manufactured (Figure 1-11).

Flanged end connections can be used in a temperature range from absolute zero ( $-273^{\circ} \mathrm{F}$ ) to approximately $1500^{\circ} \mathrm{F}\left(815^{\circ} \mathrm{C}\right)$. They are used on all valve sizes. The most common flanged end connections include flat face, raised face, and ring type joint.

Welded ends on control valves are leak tight at all pressures and temperatures and are economical in initial cost (Figure 1-12). Welded end valves are more difficult to remove from the line and are obviously limited to weldable materials. Welded
ends come in two styles, socket weld and buttweld.

\section*{Shutoff Capability}

Some consideration must be given to a valve's shutoff capability, which usually is rated in terms of Classes specified in ANSI/FCI70-2 (Table 1-4). In service, shutoff leakage depends on many factors, including but not limited to, pressure drop, temperature, the condition of the sealing surfaces, and actuator force.

Since shutoff ratings are based on standard test conditions that can be very different from service conditions, service leakage cannot be predicted accurately. However, the shutoff Class provides a good basis for comparison among valves of similar configuration. It is not uncommon for valve users to overestimate the shutoff class required.

Since tight shutoff valves generally cost more both in initial cost as well as in later maintenance expense, serious consideration is warranted. Tight shutoff is particularly important in high-pressure valves, considering that leakage in these applications can lead to the ultimate destruction of the trim. Special precautions in seat material selection, seat preparation and seat load are necessary to ensure success.

\section*{Flow Capacity}

Finally, the criterion of capacity or size can be an overriding constraint on selection. For very large lines, sliding-stem valves are more expensive than rotary types. On the other hand, for very small flows, a suitable rotary valve may not be available.

If future plans call for significantly larger flow, then a sliding-stem valve with replaceable restricted trim may be the answer. The trim can be changed to full size trim to accommodate higher flow rates at less cost than replacing the entire valve body assembly.

Rotary style products generally have much higher maximum capacity than sliding-stem valves for a given body size. This fact makes rotary products attractive in applications where the pressure drop available is rather small. However, it is of little or no advantage in high-pressure drop applications such as pressure regulation or letdown.

\section*{Conclusion}

We may simplify the process of selection as follows:

For most general applications, it makes sense both economically as well as technically to use sliding-stem valves for lower flow ranges, ball valves for intermediate capacities, and high performance butterfly valves for the very largest required flows.

For sizes less than NPS 3, general-purpose slid-ing-stem valves provide an exceptional value. For a minimal price premium over rotary products, they offer unparalleled performance, flexibility and service life. In NPS 3 size and larger, the premium for these devices over rotary products is warranted. For severe service applications the most frequently used and often the only available product is the sliding-stem valve.

Applications ranging from NPS 4 to NPS 6 are best served by such transitional valve styles as the eccentric plug valve or the ball valve. These products have minimal body material and therefore lower cost. They also offer higher capacity levels than globe designs.

In sizes NPS 8 and larger, applications tend to have lower pressures and pressure drops than in smaller valve sizes. This gives rise to the possibility of using high-performance butterfly valves. These valves are economical, can offer tight shutoff as well as provide good control capability, not to mention capacity benefits well beyond those of globe and high-performance rotary valves.

Special considerations may require out of the ordinary valve solutions. There are valve designs and special trims available to handle high noise applications, cavitation, high pressure, high temperature and combinations of these conditions.

After going through all the criteria for a given application, the selection process may point to several types of valves. From there on, selection becomes a matter of price versus capability as discussed here, coupled with the inevitable personal and institutional preferences. Since no single control valve package is cost-effective over the full range of applications, it is important to keep an open mind to alternative choices.

\begin{table}
\captionsetup{labelformat=empty}
\caption{Table 1-2. Major Categories and Subcategories of Control Valves, with Typical General Characteristics}
\begin{tabular}{|l|l|l|l|l|l|l|l|}
\hline Valve Style & Main Characteristics & Typical Size Range, NPS & Typical Standard Body Materials & Typical Standard End Connection & Typical Pressure Ratings & Relative Flow Capacity & Relative Shutoff Capability \\
\hline Regular Sliding-stem & Heavy Duty Versatile & 1 to 24 & Carbon Steel Cast Iron Stainless & ASME Flanged Welded Screwed & To ASME CL2500 & Moderate & Excellent \\
\hline Bar Stock & Machined from Bar Stock & 1/2 to 3 & Variety of Alloys & Flangeless Screwed & To ASME CL600 & Low & Excellent \\
\hline Economy Sliding-stem & Light Duty Inexpensive & $1 / 2$ to 2 & Bronze Cast Iron Carbon Steel & Screwed & To ASME CL125 & Moderate & Good \\
\hline Thru-Bore Ball & On-Off Service & 1 to 24 & Carbon Steel Stainless & Flangeless & To ASME CL900 & High & Excellent \\
\hline Segmented Ball & Characterized for Throttling & 1 to 24 & Carbon Steel Stainless & Flangeless Flanged & To ASME CL600 & High & Excellent \\
\hline Eccentric Plug & Erosion Resistance & 1 to 8 & Carbon Steel Stainless & Flanged & To ASME CL600 & Moderate & Excellent \\
\hline Swing-Thru Butterfly & No Seal & 2 to 96 & Carbon Steel Cast Iron Stainless & Flangeless Lugged Welded & To ASME CL2500 & High & Poor \\
\hline Lined Butterfly & Elastomer or TFE Liner & 2 to 96 & Carbon Steel Cast Iron Stainless & Flangeless Lugged & To ASME CL300 & High & Good \\
\hline High Performance Butterfly & Offset Disk General Service & 2 to 72 & Carbon Steel Stainless & Flangeless Lugged & To ASME CL600 & High & Excellent \\
\hline
\end{tabular}
\end{table}

\begin{table}
\captionsetup{labelformat=empty}
\caption{Table 1-3. Control Valve Characteristic Recommendations
Liquid Level Systems}
\begin{tabular}{|l|l|}
\hline Control Valve Pressure Drop & Best Inherent Characteristic \\
\hline Constant $\Delta \mathrm{P}$ & Linear \\
\hline Decreasing $\Delta \mathrm{P}$ with increasing load, $\Delta \mathrm{P}$ at maximum load $>20 \%$ of minimum load $\Delta \mathrm{P}$ & Linear \\
\hline Decreasing $\Delta \mathrm{P}$ with increasing load, $\Delta \mathrm{P}$ at maximum load $<20 \%$ of minimum load $\Delta \mathrm{P}$ & Equal-percentage \\
\hline Increasing $\Delta \mathrm{P}$ with increasing load, $\Delta \mathrm{P}$ at maximum load < 200\% of minimum load $\Delta \mathrm{P}$ & Linear \\
\hline Increasing $\Delta \mathrm{P}$ with increasing load, $\Delta \mathrm{P}$ at maximum load $>200 \%$ of minimum load $\Delta \mathrm{P}$ & Quick Opening \\
\hline
\end{tabular}
\end{table}

\section*{Pressure Control Systems}

\begin{tabular}{|l|l|}
\hline Application & Best Inherent Characteristic \\
\hline Liquid Process & Equal-Percentage \\
\hline Gas Process, Large Volume (Process has a receiver, Distribution System or Transmission Line Exceeding 100 ft . of Nominal Pipe Volume), Decreasing $\Delta \mathrm{P}$ with Increasing Load, $\Delta \mathrm{P}$ at Maximum Load $>20 \%$ of Minimum Load $\Delta \mathrm{P}$ & Linear \\
\hline Gas Process, Large Volume, Decreasing $\Delta \mathrm{P}$ with Increasing Load, $\Delta \mathrm{P}$ at Maximum Load < 20\% of Minimum Load $\Delta \mathrm{P}$ & Equal-Percentage \\
\hline Gas Process, Small Volume, Less than 10 ft . of Pipe between Control Valve and Load Valve & Equal-Percentage \\
\hline
\end{tabular}

\section*{Flow Control Processes}

\begin{tabular}{|l|l|l|l|}
\hline \multicolumn{2}{|c|}{Application} & \multicolumn{2}{|c|}{Best Inherent Characteristic} \\
\hline Flow Measurement Signal to Controller & Location of Control Valve in Relation to Measuring Element & Wide Range of Flow Set Point & Small Range of Flow but Large $\Delta \mathrm{P}$ Change at Valve with Increasing Load \\
\hline Proportional to Flow & In Series & Linear & Equal-Percentage \\
\hline & In Bypass* & Linear & Equal-Percentage \\
\hline Proportional to Flow Squared & In Series & Linear & Equal-Percentage \\
\hline & In Bypass* & Equal-Percentage & Equal-Percentage \\
\hline \multicolumn{4}{|l|}{*When control valve closes, flow rate increases in measuring element.} \\
\hline
\end{tabular}

\begin{table}
\captionsetup{labelformat=empty}
\caption{Table 1-4. Control Valve Leakage Standards}
\begin{tabular}{|l|l|l|l|l|l|l|}
\hline ANSI I FCI 70-2 and IEC 60534-4 & \multicolumn{3}{|c|}{Maximum Leakage} & Test Medium & \multicolumn{2}{|c|}{Pressure and Temperature} \\
\hline Class II & \multicolumn{3}{|c|}{0.5\% valve capacity at full travel} & Air & \multicolumn{2}{|c|}{Service $\Delta \mathrm{P}$ or 50 psig ( 3.4 bar differential), whichever is lower, at $50^{\circ}$ or $125^{\circ} \mathrm{F}\left(10^{\circ}\right.$ to $\left.52^{\circ} \mathrm{C}\right)$} \\
\hline Class III & \multicolumn{3}{|c|}{0.1\% valve capacity at full travel} & Air & \multicolumn{2}{|c|}{Service $\Delta \mathrm{P}$ or 50 psig ( 3.4 bar differential), whichever is lower, at $50^{\circ}$ or $125^{\circ} \mathrm{F}\left(10^{\circ}\right.$ to $\left.52^{\circ} \mathrm{C}\right)$} \\
\hline Class IV & \multicolumn{3}{|c|}{0.01\% valve capacity at full travel} & Air & \multicolumn{2}{|c|}{Service $\Delta \mathrm{P}$ or 50 psig ( 3.4 bar differential), whichever is lower, at $50^{\circ}$ or $125^{\circ} \mathrm{F}\left(10^{\circ}\right.$ to $\left.52^{\circ} \mathrm{C}\right)$} \\
\hline Class V & \multicolumn{3}{|c|}{$5 \times 10^{-4} \mathrm{~mL} / \mathrm{min} /$ psig $/$ inch port dia. ( 5 $\times 10^{-12} \mathrm{~m}^{3} / \mathrm{sec} / \Delta \mathrm{bar} / \mathrm{mm}$ port dia)} & Water & \multicolumn{2}{|c|}{Service $\Delta \mathrm{P}$ at $50^{\circ}$ or $125^{\circ} \mathrm{F}\left(10^{\circ}\right.$ to $\left.52^{\circ} \mathrm{C}\right)$} \\
\hline Class VI & \multicolumn{2}{|r|}{Nominal Port Diameter} & Bubbles per Minute & mL per Minute & Test Medium & Pressure \& Temperature \\
\hline & \multirow{9}{*}{\begin{tabular}{l}
In \\
1 \\
1-1/2 \\
2 \\
2-1/2 \\
3 \\
4 \\
6 \\
8
\end{tabular}} & \begin{tabular}{l}
mm \\
25 \\
38 \\
51 \\
64 \\
76 \\
102 \\
152 \\
203
\end{tabular} & & & & \multirow{9}{*}{Service $\Delta \mathrm{P}$ or 50 psig (3.4 bar differential), whichever is lower, at $50^{\circ}$ or $125^{\circ} \mathrm{F}\left(10^{\circ}\right.$ to $\left.52^{\circ} \mathrm{C}\right)$} \\
\hline & & & & & & \\
\hline & & & & & & \\
\hline & & & & & & \\
\hline & & & & & Air & \\
\hline & & & \begin{tabular}{l}
1 \\
2 \\
3 \\
4 \\
6 \\
11 \\
27 \\
45
\end{tabular} & \begin{tabular}{l}
0.15 \\
0.30 \\
0.45 \\
0.60 \\
0.90 \\
1.70 \\
4.00 \\
6.75
\end{tabular} & & \\
\hline & & & & & & \\
\hline & & & & & & \\
\hline & & & & & & \\
\hline
\end{tabular}
\end{table}

\footnotetext{
Copyright 1976 Fluid Controls Institute, Inc. Reprinted with permission.
}

\section*{Packing Materials and Systems}

This section provides information and insight to help in selection of packing systems. Application guidelines for each packing selection have been developed to aid in the packing selection process. These guidelines were developed based on test results of various packing systems conducted in Fisher's technical center. Exceeding these guidelines may result in reduced service life.

The ratings for these systems do not affect the valve pressure/temperature class rating. Traditional valve selection entails selecting a valve design based on pressure and temperature capabilities, flow characteristics, and material compatibility. An additional factor-packing selection-is now a critical factor in the valve selection process.

Proper packing selection is being driven in the United States by the Clean Air Act Amendments, subsequent Environmental Protection Agency (EPA) regulations, and our customers' increasing concern for improved packing performance (less maintenance and longer service life.)

In recent years, packing selection has been primarily based on process temperature; that is, PTFE was selected for temperatures below $450^{\circ} \mathrm{F}$ ( $232^{\circ} \mathrm{C}$ ), and graphite was selected for temperatures above $450^{\circ} \mathrm{F}\left(232^{\circ} \mathrm{C}\right)$. Considerations now include the effect of packing friction on process control, hysteresis, seal quality, and cycle life.

Given the variety of process applications and installation conditions, these variables are difficult to quantify. A relative packing performance comparison can be made that provides an engineered approach to the packing selection process.

Clarification of trade names is required for proper understanding of the Table 1-5 shown in this publication. From the perspective of Fisher, ENVIROSEAL ${ }^{\text {™ }}$ packing is defined as an advanced system using a "compact", live-load spring design. From a user perspective, ENVIRO-SEAL packing is most
typically thought of as an emission-reducing packing system; however, as shown in the following chart and graphs, it is highly useful in non-environmental applications as well.

Although other packing materials and combinations of packing materials are available, the recommendations for nearly all applications are listed in Table 1-5. Simply select the appropriate packing based on pressure, temperature, leakage requirements, service life required, etc. Use the charts for additional guidance.

The packing selection guidelines in Table 1-5 present two categories of service conditions. The first category defines those packing systems designed for environmental or fugitive emission applications where 500 parts per million volume (ppmv) seal performance is required.

The second category defines application guidelines for non-environmental services. Depending on category requirements, different pressure/temperature guidelines have been established for the packing systems.

In addition, a given packing design has certain characteristics concerning seal performance, service life, and friction. The pressure and temperature guidelines and the relative comparison of these characteristics are defined in Table 1-5 and the supporting charts.

Keep in mind that for non-environmental applications these are guidelines and are not intended as the ultimate limit. Exceeding the pressure guidelines for packing may be required; however, depending on how much the guidelines are exceeded, a reduction in total life span can be expected.

With flexible graphite packing this same logic applies to temperature. The recommended pressure I temperature limits for environmental applications using Fisher ENVIRO-SEAL packing cannot be exceeded without compromising sealing integrity.

\begin{table}
\captionsetup{labelformat=empty}
\caption{Table 1-5. Packing Selection Guidelines for Sliding-Stem Valves}
\begin{tabular}{|l|l|l|l|l|l|l|l|}
\hline \multirow{2}{*}{Packing System} & \multicolumn{2}{|c|}{Maximum Pressure \& Temperature Limits for 500 PPM Service ${ }^{(1)}$} & \multicolumn{2}{|c|}{Application Guideline for Nonenvironmental Service ${ }^{(1)}$} & \multirow{2}{*}{Seal Performance Index} & \multirow{2}{*}{Service Life Index} & \multirow{2}{*}{Packing Friction ${ }^{(2)}$} \\
\hline & Customary U.S. & Metric & Customary U.S. & Metric & & & \\
\hline Single PTFE V-Ring & 300 psig 0 to $200^{\circ} \mathrm{F}$ & 20.7 bar -18 to $93^{\circ} \mathrm{C}$ & See figure 1-16 -50 to $450^{\circ} \mathrm{F}$ & See figure 1-16 -46 to $232^{\circ} \mathrm{C}$ & Better & Long & Very low \\
\hline ENVIRO-SEAL PTFE & See figure 1-15 -50 to $450^{\circ} \mathrm{F}$ & See figure 2 -46 to $232^{\circ} \mathrm{C}$ & See figure 1-16 -50 to $450^{\circ} \mathrm{F}$ & See figure 1-16 -46 to $232^{\circ} \mathrm{C}$ & Superior & Very long & Low \\
\hline ENVIRO-SEAL Duplex & 750 psig -50 to $450^{\circ} \mathrm{F}$ & 51.7 bar -46 to $232^{\circ} \mathrm{C}$ & See figure 1-16 -50 to $450^{\circ} \mathrm{F}$ & See figure 1-16 -46 to $232^{\circ} \mathrm{C}$ & Superior & Very long & Low \\
\hline KALREZ ${ }^{\circledR}$ with PTFE (KVSP 400) ${ }^{(3)}$ & 350 psig 40 to $400^{\circ} \mathrm{F}$ & 24.1 bar 4 to 204 & See figure 1-16 -40 to $400^{\circ} \mathrm{F}$ & See figure 1-16 -40 to $204^{\circ} \mathrm{C}$ & Superior & Long & Low \\
\hline ENVIRO-SEAL Graphite ULF & 1500 psig 20 to $600^{\circ} \mathrm{F}$ & 103 bar -7 to $315^{\circ} \mathrm{C}$ & 3000 psig -325 to $700^{\circ} \mathrm{F}$ & 207 bar -198 to $371^{\circ} \mathrm{C}$ & Superior & Very long & High \\
\hline HIGH-SEAL Graphite with PTFE & 1500 psig 20 to $600^{\circ} \mathrm{F}$ & 103 bar -7 to $315^{\circ} \mathrm{C}$ & 4200 psig ${ }^{(4)}$ -325 to $700^{\circ} \mathrm{F}$ & 290 bar ${ }^{(4)}$ -198 to $317^{\circ} \mathrm{C}$ & Superior & Very long & High \\
\hline HIGH-SEAL Graphite & ------ & ------ & 4200 psig ${ }^{(4)}$ -325 to $1200^{\circ} \mathrm{F}^{(5)}$ & 290 bar ${ }^{(4)}$ -198 to $649^{\circ} \mathrm{C}(5)$ & Better & Very long & Very high \\
\hline Braided Graphite Filament & ---- - - & ---- - - & 1500 psig -325 to $1000^{\circ} \mathrm{F}^{(5)}$ & 103 bar -198 to $538^{\circ} \mathrm{C}(5)$ & Acceptable & Acceptable & High \\
\hline \multicolumn{8}{|c|}{\begin{tabular}{l}
1. The values shown are only guidelines. These guidelines can be exceeded, but shortened packing life or increased leakage might result. The temperature ratings apply to the actual packing temperature, not to the process temperature. \\
2. See Catalog 14 for actual friction values. \\
3. The KALREZ pressure/temperature limits referenced in this bulletin are for Fisher Controls valve applications only. DuPont may claim higher limits. \\
4. Except for the $3 / 8$-inch ( 9.5 mm ) stem, 1600 psig ( 110 bar ). \\
5. Except for oxidizing service, -325 to $700^{\circ} \mathrm{F}\left(-198\right.$ to $\left.371^{\circ} \mathrm{C}\right)$.
\end{tabular}} \\
\hline
\end{tabular}
\end{table}

\section*{Packing Set Possibilities}

\section*{Single PTFE V-Ring Packing (Sliding-Stem and Rotary Valves)}

The single PTFE V-ring arrangement uses a coil spring, as in the easy-e ${ }^{\text {TM }}$ valves, and meets the EPA 500 ppmv criteria, assuming that the pressure does not exceed 300 psig (20.7 bar) and the temperature is between $0^{\circ} \mathrm{F}$ and $200^{\circ} \mathrm{F}$ (-18 and $93^{\circ} \mathrm{C}$ ). This packing arrangement offers very good seal performance with the lowest packing friction and usually the lowest cost.

\section*{ENVIRO-SEAL PTFE Packing (Sliding-Stem and Rotary Valves)}

The ENVIRO-SEAL PTFE arrangement is suitable for environmental applications on services up to 750 psig and $450^{\circ} \mathrm{F}$ ( 51.7 bar and $233^{\circ} \mathrm{C}$ ). The sealing capability is superior. The ENVIRO-SEAL PTFE packing system is designed to operate at a nearly constant high stress. This design approach results in an increase in stem friction. Typically, the slight increase in stem friction does not cause problems with actuator sizing or process control, such as hysteresis. It is always recommended that actuator sizing be verified whenever you select a different packing material.

\section*{Flexible Graphite Packing Material (Sliding-Stem Only)}

It is important to understand some of the issues associated with the base material that is common to all high temperature graphite packing systems. The single most important issue is the potential for galvanic corrosion in valves in storage that have graphite packing system installed.

Fisher uses only the highest grades of base flexible graphite material that contain a non-metallic, inorganic, passivating inhibitor for galvanic corrosion resistance. All Fisher graphite packing systems (with the exception of nuclear applications) also include sacrificial zinc washers to prevent galvanic corrosion.

However, even with these preventive measures, under humid conditions, in the presence of chlorides, with air or oxygen present, there is potential for galvanic corrosion of the valve stem. Because there are numerous variables associated with galvanic corrosion it is near impossible to predict when it may occur.

The best policy is to remove the packing if the valve is to be stored for a long period. This, however, may create a safety issue if someone were to use the valve not realizing that there was no packing in the valve. For this exact reason all Fisher valves are supplied with the packing installed.

\section*{ENVIRO-SEAL Graphite ULF (Sliding-Stem and Rotary Valves)}

ENVIRO-SEAL Graphite ULF packing is designed for environmental applications from 300 to $600^{\circ} \mathrm{F}$ ( 149 to $316^{\circ} \mathrm{C}$ ), or for those applications where fire safety is a concern and graphite packing is desired. The ENVIRO-SEAL Graphite ULF arrangement can also be used with higher pressures up to 1500 psig (103 bar) and still maintain the 500 ppmv EPA leakage criteria.

ENVIRO-SEAL Graphite ULF packing systems were developed by utilizing the benefits of both PTFE and graphite components. These special packing systems provide the firesafe capability of graphite packing along with reduced friction advantages of PTFE packing. Thus, ENVIRO-SEAL Graphite ULF packing systems provide a lower friction, lower emission, fire-tested solution for applications with process temperatures up to $316^{\circ} \mathrm{C}$ ( $600^{\circ} \mathrm{F}$ ). ENVIRO-SEAL Graphite ULF packing systems were tested in accordance with API Standard 589, "Fire Test Evaluation of Valve Stem Packing", second edition. See Figure 1-14 for applications guidelines for 500 ppm service. Figure 1-17 shows the ENVIRO-SEAL Graphite ULF packing system.

\section*{HIGH-SEAL ${ }^{\text {™ }}$ Graphite with PTFE for Environmental Applications (Sliding-Stem Only)}

The HIGH-SEAL packing system features liveloading and unique packing ring arrangements for consistent, long-term sealing performance. It is offered without PTFE washers for nuclear service where PTFE is prohibited and with PTFE washers for all other applications.

The primary advantage of the HIGH-SEAL packing system arrangement is the use of large Belleville springs, which can be calibrated with a load scale. The load scale provides a visual indication of packing load, making it easier to determine when additional torque might be required.

HIGH-SEAL packing systems have a disadvantage, from an installation perspective. This disadvantage is that the actuator cannot be removed from the valve without removing the Belleville springs.

The HIGH-SEAL graphite packing system provides a service life that is very long compared to other graphite packing arrangements.

\section*{Non-Environmental Services}

For the non-environmental pressure/temperature guidelines, using ENVIRO-SEAL and HIGH-SEAL packing systems can extend service life.

As service pressures and temperatures increase, the ENVIRO-SEAL packing systems provide a significant step change in performance, compared to the traditional single PTFE V-ring or braided graphite filament arrangements. For example, an ASME CL1500 (HP valve) application at 2000 psig and $200^{\circ} \mathrm{F}$ ( 137 bar and $93^{\circ} \mathrm{C}$ ) frequently required packing maintenance. The HIGH-SEAL packing system with PTFE washers was installed, significantly reducing maintenance requirements. This system is rated to 420 psig and $700^{\circ} \mathrm{F}$ (290 bar and $371^{\circ} \mathrm{C}$ ). The ENVIRO-SEAL packing system or compact Belleville spring arrangement is rated to 3000 psig and $700^{\circ} \mathrm{F}$ ( 20.7 bar and $371^{\circ} \mathrm{C}$ ).

Table 1-5 shows that the braided graphite filament arrangement is limited to 1500 psig ( 103 bar). Due to its construction, braided graphite filament cannot sustain high packing stress levels. Over time, the braided graphite filament will break down and compress, and sealing force will be lost. Due to these characteristics, braided graphite filament will not provide the required seal performance for environmental services. The braided graphite filament arrangement is also susceptible to stick-slip action, which might cause process control deviations.

\section*{Rotary Valve Considerations}

The basic principles of sealing a rotary shaft are the same as sealing a sliding stem. However, experience shows that sealing the shaft on a rotary valve is less difficult than on sliding stem applications. The rotary motion does not tend to remove material from the packing box as does the sliding stem motion. Also, many of the rotary valve applications tend to be lower pressure applications than sliding stem valve services. As with sliding stem valves, the basic material recommendation for rotary valve packing is either PTFE or flexible graphite.

\section*{Single Packing Arrangements}

Used in most applications for a durable, yet economical package.

\section*{Double Packing Arrangements}

Where an especially tight seal is required, double packing is available. Consisting of two stacks of packing and a spacer, double packing arrangements have more packing on the actuator side if a lubricating connection is used.

\section*{Leak-Off Packing Arrangements}

Certain rotary valve applications require that any leakage from the inner set of packing be detected and channeled away before it can leak through the outer set to the atmosphere. Leak-off packing arrangements are designed for this purpose.

Some standard packing arrangements, such as double PTFE V-ring, that have packing on either side of a lubricator connection can also be used for leak-off applications. However, standard packing arrangements are not specifically designed for leak-off applications and do not have a suitable ratio of packing on either side of the lubricator.

\section*{Purged Packing Arrangement}

Certain rotary valve applications require that a lantern gland and a tapped pipe connection be provided inboard of the packing itself to permit purging of any accumulated deposits around the valve shaft and bushing. This arrangement is recommended for handling fluids with entrained solids and where fluids condense or solidify with loss of temperature.

\section*{Process Fluid Compatibility and Temperature Ranges}

Fisher's published literature lists packing types that are used with various process fluids. However, some process fluids may not be compatible with the packing throughout the entire temperature range. If in doubt about the compatibility of Fisher's packing material with a process fluid of a specific concentration and temperature, consult your Fisher Representative sales office.

Published temperature ranges refer to temperatures in the packing box. When using any packing at low temperatures, frost allowed to form on the shaft can damage the packing. For a given process temperature, the packing box temperature depends on several factors. Contact the Fisher sales representative for information on packing box temperatures.

\section*{Conclusion}

It is important to recognize that many parameters affect seal performance and service life. Even if the optimum design is selected, other factors such as stem finish, packing bore finish, and installation practices will have an effect on performance.

The knowledge gained by Fisher as a result of the ENVIRO-SEAL and HIGH-SEAL packing development program has provided an opportunity to help you "engineer" the packing selection. Proper selection has a bottom line result; that is, increased service life and reduced maintenance.

If you need a more detailed engineering discussion of the design principles affecting packing seal design, contact your Fisher sales office or sales representative.

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-022.jpg?height=985&width=1460&top_left_y=265&top_left_x=357}
\captionsetup{labelformat=empty}
\caption{Figure 1-13. Application Guidelines Chart for 500 PPM Service}
\end{figure}

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-022.jpg?height=1026&width=1584&top_left_y=1352&top_left_x=249}
\captionsetup{labelformat=empty}
\caption{Figure 1-14. Application Guidelines Chart for Non-Environmental Service}
\end{figure}

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-023.jpg?height=1708&width=1706&top_left_y=271&top_left_x=241}
\captionsetup{labelformat=empty}
\caption{Figure 1-15. Typical Packing Examples for Sliding-Stem Valves}
\end{figure}

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-024.jpg?height=1895&width=1714&top_left_y=268&top_left_x=241}
\captionsetup{labelformat=empty}
\caption{NOTE: LEAD-OFF TAPPING AND PIPE PLUG ARE OPTIONAL}
\end{figure}

Figure 1-16. Typical Packing Examples for Sliding-Stem Valves

\begin{figure}
\includegraphics[width=\textwidth]{https://cdn.mathpix.com/cropped/2025_08_28_f30f0bb3b7b14bdf7722g-025.jpg?height=837&width=1690&top_left_y=281&top_left_x=266}
\captionsetup{labelformat=empty}
\caption{Figure 1-17. Typical ENVIRO-SEAL Packing Arrangements for Rotary Valves}
\end{figure}